import { Inter } from 'next/font/google'
import './globals.css'
import Navber from './component/Navber'
import { GlobalState } from '@/context/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EYE-Commerce',
  description: 'Generated by eye Commerce',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <div>  <Navber></Navber>
       <main> {children}</main>
        </div>
        </GlobalState>
      
        </body>
    </html>
  )
}
